#!/usr/bin/python3

import flask
from flask.config import Config as FlaskConfig


import lapis.builds
import lapis.config as config

baseurl = config.get('baseurl')
print(config.list())

print(FlaskConfig.values)

def main():
    from . import app
    app.run(config)

app = flask.Flask(__name__)
app.config["DEBUG"] = True
# set flask port to config


app.config['PORT'] = config.get('port')


@app.route(baseurl, methods=['GET'])
def home():
    return '''
    This is the Lapis Build system Backend server. Only API requests are supported.
    '''

@app.route(baseurl + '/build', methods=['POST'])
def build():
    # get file upload from request
    file = flask.request.files['file']
    # save file to disk
    filename = file.filename
    file.save(filename)
    # run mock with file
    return '''
    This is the Lapis Build system Backend server. Only API requests are supported.
    '''
# if it's a get request, return the list of builds
@app.route(baseurl + '/build' , methods=['GET'])
def get_builds():
    # return array
    return builds.builds(10).to_json()


@app.route('/api/build/<build_id>', methods=['GET'])
def get_build(build_id):
    return '''
    This is the Lapis Build system Backend server. Only API requests are supported.
    '''

print('Lapis Build system Backend server started.')

app.run()